---
name: Docker Image Build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  REGISTRY: harbor.octanner.io
  REPO: harbor.octanner.io/cloudops/aws-encryption-provider
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Login to ${{ env.REGISTRY }}
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.HARBOR_GITHUB_USERNAME }}
        password: ${{ secrets.HARBOR_GITHUB_PASSWORD }}

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d')"

    - name: Build the Docker image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ env.REPO }}:release-${{ github.run_number }}
